### ISSUE TITLE
Navigation and NavigationBarHiddenMessage

### ISSUE THREAD

**Issue by gridr-ch** [benhysell/V.FlyoutTest#1]
Hi Ben,

Thank you for your nice example, it is very helpful, especially for me as a beginer in Xamarin and mobile development.

I am currently implementing an app for Android and iOS and want to use both MvvmCross and the FlyoutNavigationController, so I implemented it similar to your example. 

The only thing that does not work as desired yet is the NavigationBar. When using the NavigationBarHiddenMessage to show and hide the NavigationBar, it flickers and shows black fragments. When sliding to navigate back, but not finishing the slide and going back to the detail page, the navigation bar will be (and stay) hidden, so the app has to be killed.

Did you find a better solution for this in the meantime?

Regards,
Marcel

**Comment by benhysell** [comment]
Thank you, I'm glad it is helping you out!
1. I have not found a way to slay the flicker problem when pushing another View and using the NavigationBarHiddenMessage.  I have not played around if I could change when that message is generated/executed to make that a more seamless experience.  I'm living with it now as a known bug.
2. On the FlyoutNavigation control I disabled swipe to reveal, thus ensuring the user has to hit the 'back' button to come back to the home view controller.

```
 navigation.ShouldReceiveTouch += (sender, touch) =>
            {
                return false;
            };
```

This way I can ensure the message to show the navigation bar is sent every time.

**Comment by gridr-ch** [comment]
Hi Ben, 

Thank you for your response. 
I worked around this swipe-issue myself by using the ViewDidDisappear method instead of ViewWillDisappear. 

Anyway, I'll try to find a solution for the NavigationBar. I'll let you know if I get lucky.

**Comment by benhysell** [comment]
Marcel,

Why don't you open another issue for the NavigationBar so we can track it.

-ben
